name = "emerald"
main = "_worker.js"
compatibility_date = "2023-05-26"
node_compat = true
workers_dev = true

[vars]
PROXYIP = "211.230.110.231:50008"
UUID = "6f361a6f-318e-49cd-b71e-1e8d568b9888"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
